In [1]:
url = 'https://finance.naver.com/marketindex/exchangeList.nhn'

In [4]:
import urllib.request
from bs4 import BeautifulSoup

In [5]:
page = urllib.request.urlopen(url)

In [6]:
soup = BeautifulSoup(page, 'html.parser')

In [7]:
result = soup.select('td.tit > a')

In [ ]:
result # 확인

In [14]:
list1=[]
for r in result:
    list1.append(r.string.strip())

#    print(r.string.strip()) #strip으로 공백 제거

In [18]:
result2 = soup.select('td.sale')
list2=[]
for r in result2:
    list2.append(r.string)

In [30]:
final = zip(list1, list2)
final_set = set(final)

In [31]:
final_set

{('남아프리카 공화국 ZAR', '75.25'),
 ('노르웨이 NOK', '131.41'),
 ('뉴질랜드 NZD', '806.62'),
 ('대만 TWD', '40.00'),
 ('덴마크 DKK', '181.26'),
 ('러시아 RUB', '15.08'),
 ('말레이시아 MYR', '275.49'),
 ('멕시코 MXN', '55.67'),
 ('몽골 MNT', '0.39'),
 ('미국 USD', '1,120.00'),
 ('바레인 BHD', '2,970.59'),
 ('방글라데시 BDT', '13.21'),
 ('베트남 VND 100', '4.87'),
 ('브라질 BRL', '208.54'),
 ('브루나이 BND', '839.61'),
 ('사우디아라비아 SAR', '298.57'),
 ('스웨덴 SEK', '133.68'),
 ('스위스 CHF', '1,244.44'),
 ('싱가포르 SGD', '839.61'),
 ('아랍에미리트 AED', '304.92'),
 ('영국 GBP', '1,538.32'),
 ('오만 OMR', '2,909.09'),
 ('요르단 JOD', '1,579.69'),
 ('유럽연합 EUR', '1,347.86'),
 ('이스라엘 ILS', '340.26'),
 ('이집트 EGP', '71.50'),
 ('인도 INR', '15.37'),
 ('인도네시아 IDR 100', '8.02'),
 ('일본 JPY (100엔)', '1,061.56'),
 ('중국 CNY', '173.64'),
 ('체코 CZK', '52.29'),
 ('칠레 CLP', '1.52'),
 ('카자흐스탄 KZT', '2.67'),
 ('카타르 QAR', '307.55'),
 ('캐나다 CAD', '877.50'),
 ('쿠웨이트 KWD', '3,698.20'),
 ('태국 THB', '37.28'),
 ('터키 TRY', '159.18'),
 ('파키스탄 PKR', '6.98'),
 ('폴란드 PLN', '300.54'),
 ('필리핀 PHP', '23.31'),
 ('헝가리 HUF', '3.77'),
 ('호주 AUD', '859.66'),
 ('홍콩 HKD', '144.46')}

In [34]:
import pandas as pd
url = 'https://finance.naver.com/marketindex/exchangeList.nhn'
df = pd.read_html(url)

In [35]:
df

[              통화명    매매기준율       현찰                송금           미화환산율
               통화명    매매기준율     사실 때     파실 때    보내실 때    받으실 때  미화환산율
 0          미국 USD  1120.00  1139.60  1100.40  1130.90  1109.10  1.000
 1        유럽연합 EUR  1348.09  1374.91  1321.27  1361.57  1334.61  1.204
 2   일본 JPY (100엔)  1061.61  1080.18  1043.04  1072.01  1051.21  0.948
 3          중국 CNY   173.63   182.31   164.95   175.36   171.90  0.155
 4          홍콩 HKD   144.47   147.31   141.63   145.91   143.03  0.129
 5          대만 TWD    40.00    45.24    37.20     0.00     0.00  0.036
 6          영국 GBP  1537.76  1568.05  1507.47  1553.13  1522.39  1.373
 7          오만 OMR  2909.09  3167.99  2734.55     0.00     0.00  2.597
 8         캐나다 CAD   877.54   894.82   860.26   886.31   868.77  0.784
 9         스위스 CHF  1244.72  1269.24  1220.20  1257.16  1232.28  1.111
 10        스웨덴 SEK   133.61   136.88   130.34   134.94   132.28  0.119
 11         호주 AUD   859.60   876.53   842.67   868.19   851.01  0.768
 12       뉴질랜드 NZD   806.74   822.63   790.85   814.80   798.68  0.720
 13         체코 CZK    52.32    56.76    47.62    52.89    51.75  0.047
 14         칠레 CLP     1.52     1.64     1.40     0.00     0.00  0.001
 15         터키 TRY   158.98     0.00     0.00   160.72   157.24  0.142
 16         몽골 MNT     0.39     0.00     0.00     0.00     0.00  0.000
 17       이스라엘 ILS   340.58   374.63   313.34     0.00     0.00  0.304
 18        덴마크 DKK   181.31   185.75   176.87   183.12   179.50  0.162
 19       노르웨이 NOK   131.28   134.49   128.07   132.59   129.97  0.117
 20    사우디아라비아 SAR   298.57   317.37   277.97   301.55   295.59  0.267
 21       쿠웨이트 KWD  3698.20  3938.58  3402.35  3735.18  3661.22  3.302
 22        바레인 BHD  2970.59  3160.70  2732.95  3000.29  2940.89  2.652
 23     아랍에미리트 AED   304.92   321.69   283.89   307.96   301.88  0.272
 24        요르단 JOD  1579.69  1720.28  1453.32     0.00     0.00  1.410
 25        이집트 EGP    71.59     0.00     0.00     0.00     0.00  0.064
 26         태국 THB    37.28    39.14    35.05    37.65    36.91  0.033
 27       싱가포르 SGD   839.49   856.19   822.79   847.88   831.10  0.750
 28      말레이시아 MYR   275.49   292.84   255.11     0.00   272.74  0.246
 29  인도네시아 IDR 100     8.01     8.57     7.21     8.09     7.93  0.007
 30        카타르 QAR   307.52     0.00     0.00     0.00     0.00  0.275
 31      카자흐스탄 KZT     2.67     0.00     0.00     0.00     0.00  0.002
 32       브루나이 BND   839.49   873.06   789.13     0.00     0.00  0.750
 33         인도 INR    15.38     0.00     0.00     0.00     0.00  0.014
 34       파키스탄 PKR     6.98     0.00     0.00     0.00     0.00  0.006
 35      방글라데시 BDT    13.21     0.00     0.00     0.00     0.00  0.012
 36        필리핀 PHP    23.31    25.64    21.40    23.54    23.08  0.021
 37        멕시코 MXN    55.67    61.23    51.00    56.22    55.12  0.050
 38        브라질 BRL   208.54   229.81   191.86     0.00   206.04  0.186
 39    베트남 VND 100     4.88     5.45     4.31     4.92     4.84  0.004
 40  남아프리카 공화국 ZAR    75.22    79.73    69.21    76.12    74.32  0.067
 41        러시아 RUB    15.09    16.14    13.44    15.24    14.94  0.014
 42        헝가리 HUF     3.77     4.12     3.47     3.81     3.73  0.003
 43        폴란드 PLN   300.58   324.62   276.54   303.88   297.28  0.268]